package com.github.tavi.lilbird.db.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.github.tavi.lilbird.models.BirdModel;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * The primary entry for the database that features a uniques {@code long} ID
 * (autogenerated), a unique non-nullable primary name (a.k.a. title)
 * and an optional common name.
 * <p>
 * Even if the database contains any other kind of data (not birds),
 * it is convenient to call each unique entry "a bird".
 */
@JsonInclude(Include.NON_NULL)
@Entity(name = "Bird")
@Table(name = "Birds")
@Data
@NoArgsConstructor
public class BirdEntry implements BirdModel {

    /**
     * Converts the latin name to a normal form.
     * <p>
     * The normal form is case-insensitive and does not include spaces.
     * 
     * @param title     The original unique name for the bird entry.
     * @return          The same name, but normalized
     */
    public static String normalize(final String title) {
        return title.toLowerCase()
                .replace("\s", "+");
    }


    @Min(value = 1, message = "The ID is always > 0")
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    private String nameLatin;

    /**
     * The normalized name is used for DB indexation and searching.
     * <p>
     * <b>Do not set this value manually; it will be set automatically.</b>.
     * 
     * @see #setNameLatin(String)
     * @see BirdEntry#normalize(String)
     */
    @NotNull
    @Schema(
        description = "The normalized title",
        example = "corvus+corax"
    )
    @Column(
        name = "name_normal",
        unique = true, 
        nullable = false
    )
    private String nameNormal;


    /**
     * Sets both displayed and normalized latin names.
     * 
     * @param nameLatin     The original unique name for the bird entry.
     * 
     * @see                 BirdEntry#normalize(String)
     */
    public void setNameLatin(final String nameLatin) {
        this.nameLatin = nameLatin;
        nameNormal = BirdEntry.normalize(nameLatin);
    }
}
