package com.github.tavi.lilbird.db.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.github.tavi.lilbird.models.BirdEntry;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * The primary entry for the database that features a uniques {@code long} ID
 * (autogenerated), a unique non-nullable primary name (a.k.a. title)
 * and an optional common name.
 * <p>
 * Even if the database contains any other kind of data (not birds),
 * it is convenient to call each unique entry "a bird".
 */
@JsonInclude(Include.NON_NULL)
@Entity
@Table(
    name = "Entries"
)
@Data
@NoArgsConstructor
public class BirdEntryEntity implements BirdEntry {

    @Min(
        value = 1,
        message = "The ID is always > 0"
    )
    @Id
    @GeneratedValue(
        strategy = GenerationType.IDENTITY
    )
    private Long id;

    
    @Column(unique = true, nullable = false)
    private String title;

    @Column(name = "common_name")
    private String commonName = null;

}
