package com.github.tavi.lilbird.db.entities;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.github.tavi.lilbird.models.BirdEntry;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * The primary entry for the database that features a uniques {@code long} ID
 * (autogenerated), a unique non-nullable primary name (a.k.a. title)
 * and an optional common name.
 * <p>
 * Even if the database contains any other kind of data (not birds),
 * it is convenient to call each unique entry "a bird".
 */
@JsonInclude(Include.NON_NULL)
@Entity
@Table(
    name = "Entries"
)
@Data
@NoArgsConstructor
public class BirdEntryEntity implements BirdEntry {

    /**
     * Converts the raw (original) bird title to a normal form
     * that can be used in searches.
     * <p>
     * The normal form is case-insensitive and does not include spaces.
     * 
     * @param title     The original unique name for the bird entry.
     * @return          The same name, but normalized
     */
    public static String normalize(final String title) {
        return title.toLowerCase()
                .replace("-", "_")
                .replace("\s", "-");
    }


    @Min(
        value = 1,
        message = "The ID is always > 0"
    )
    @Id
    @GeneratedValue(
        strategy = GenerationType.IDENTITY
    )
    private Long id;

    @Column(
        nullable = false
    )
    private String title;

    @NotNull
    @Schema(
        description = "The normalized title",
        example = "corvus-corax"
    )
    @Column(
        name = "title_id",
        unique = true, 
        nullable = false
    )
    private String titleId;

    @Column(
        name = "common_name"
    )
    private String commonName = null;


    /**
     * Sets both displayed title (raw value)
     * and ID title (normalized value) to this entity.
     * <p>
     * The normalized value is an indexed column,
     * and it may be used as an alternative to the {@code long} ID
     * for searching.
     * 
     * @param title     The original unique name for the bird entry.
     * 
     * @see             BirdEntryEntity#normalize(String)
     */
    public void setTitle(final String title) {
        this.title = title;
        titleId = BirdEntryEntity.normalize(title);
    }
}
