spring.config.import=optional:file:.env[.properties],classpath:db/db-${SPRING_PROFILE:test}.properties

spring.profiles.active=${SPRING_PROFILE:test}

server.port=8080

hibernate.connection.username=${DB_USER:sa}
hibernate.connection.password=${DB_PASSWORD:sa}

# Enable API docs and resolve properties in schemas
springdoc.api-docs.enabled=true
springdoc.api-docs.resolve-schema-properties=true
# The '/dev/**' end-points require authentification in 'dev' profile
springdoc.api-docs.path=/dev/v3/api-docs
springdoc.swagger-ui.path=/dev/swagger-ui.html
# Read API docs configuration (must be inside the "./static/" directory)
springdoc.swagger-ui.url=/openapi.yaml

# The default credentials used for authentification (super admin)
lilbird.admin.name=${SA_USER}
lilbird.admin.password=${SA_PASSWORD}

# Exception hadling
spring.mvc.problemdetails.enabled=true

# Disable lazy loading
spring.jpa.open-in-view=false