spring.config.import=optional:file:.env[.properties],classpath:db/db-${SPRING_PROFILE:test}.properties

spring.profiles.active=${SPRING_PROFILE:test}

server.port=8080

hibernate.connection.username=${DB_USER:sa}
hibernate.connection.password=${DB_PASSWORD:sa}

# The '/dev/**' end-points require authentification in 'dev' profile
springdoc.api-docs.path=/dev/v3/api-docs
springdoc.swagger-ui.path=/dev/swagger-ui.html

# The default credentials used for authentification (super admin)
spring.security.user.name=${SA_USER}
spring.security.user.password=${SA_PASSWORD}

# Exception hadling
spring.mvc.problemdetails.enabled=true