# Let Hibernate create and drop DB tables each time

liquibase.enabled=false
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create-drop

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true