spring.config.import=optional:file:.env[.properties]

spring.config.import=classpath:db/db-${SPRING_PROFILE:test}.properties
spring.profiles.active=${SPRING_PROFILE:test}

server.port=8080

hibernate.connection.username=${DB_USER:sa}
hibernate.connection.password=${DB_PASSWORD:sa}

