openapi: 3.1.0
info:
  title: LilBird API for nBirds project
  description: The API documentation for LilBird/nBirds ornithology service
servers:
  - url: http://localhost:8080
paths:
  api/v1/birds:
    $ref: './paths/birds-list.yml'
  api/v1/admin/birds:
    $ref: './paths/bird-card-post.yml'
  api/v1/birds/cards/{name_latin}:
    $ref: './paths/bird-card-get.yml'
  api/v1/birds/{id}:
    $ref: './paths/bird-entry.yml'
