package com.github.tavi.lilbird.models.entities;

import com.github.tavi.lilbird.util.NameUtils;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * The primary entry for the database that features a uniques {@code long} ID
 * (autogenerated), a unique non-nullable primary name (a.k.a. title)
 * and an optional common name.
 * <p>
 * Even if the database contains any other kind of data (not birds),
 * it is convenient to call each unique entry "a bird".
 */
@Data @NoArgsConstructor
@Entity(name = "Bird")
@Table(name = "Birds")
public class BirdEntity {

    /** Normalized latin name. */
    @Id
    @Column(name = "name_normal")
    private String nameNormal;

    /** Latin name. */
    @Column(name = "name_latin", nullable = false)
    private String nameLatin;

    /** Primary common name. */
    @Column(name = "name_main")
    private String nameMain;


    /** Sets both displayed and normalized latin names. */
    public void setNameLatin(final String nameLatin) {
        this.nameLatin = nameLatin;
        nameNormal = NameUtils.normalize(nameLatin);
    }
    
}
